-
  branches:
    only:
    - nuget  

  image: Visual Studio 2017

  before_build:
    - dotnet restore Ghpr.Console/Ghpr.Console.sln

  build_script: 
    - dotnet build Ghpr.Console/Ghpr.Console.sln /p:Configuration=Release /t:Rebuild
    
  test: off

  after_build:
    - dotnet pack -c Release "Ghpr.Console/Ghpr.Console.csproj" /p:NuspecFile="Ghpr.Console.nuspec"

  artifacts:
    - path: '**\*.nupkg'
      name: nupkg

  deploy:
    provider: NuGet
    server: 
    api_key:
      secure: crLYbWXNgfrzYazkV18cEBRKnl90ee0wjWUfZGIDhkZcZg1ZlGbbsqRdr8JLmU3O
    skip_symbols: false
    artifact: nupkg

-
  branches:
    except:
    - nuget 
    

  image: Visual Studio 2017

  before_build:
    - dotnet restore Ghpr.Console/Ghpr.Console.sln

  build_script: 
    - dotnet build Ghpr.Console/Ghpr.Console.sln /p:Configuration=Release /t:Rebuild

  test: off
