-
  branches:
    only:
    - nuget  
  
  before_build:
    - nuget restore Ghpr.Console/Ghpr.Console.sln

  build_script: 
    - msbuild Ghpr.Console/Ghpr.Console.sln /p:Configuration=Release /t:Rebuild
    
  test: off

  after_build:
    - nuget pack "Ghpr.Console/Ghpr.Console.csproj" -Prop Configuration=Release

  artifacts:
    - path: '*.nupkg'
      name: nupkg

  deploy:
    provider: NuGet
    server: 
    api_key:
      secure: crLYbWXNgfrzYazkV18cEBRKnl90ee0wjWUfZGIDhkZcZg1ZlGbbsqRdr8JLmU3O
    skip_symbols: false
    artifact: nupkg
    
-
  branches:
    except:
    - nuget 
    
  before_build:
    - nuget restore Ghpr.Console/Ghpr.Console.sln

  build_script: 
    - msbuild Ghpr.Console/Ghpr.Console.sln /p:Configuration=Release /t:Rebuild

  test: off
